-- 5월 식품들의 총매출 조회하기

-- Table
-- FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE)
-- FOOD_ORDER (PRODUCT_ID, AMOUNT, PRODUCE_DATE)

-- 조건 ; 생산일자가 2022년 5월
-- 계산 : 총매출 ; 주문량 * 식품 가격
-- 정렬 : 총매출 desc, 식품 id asc

SELECT P.PRODUCT_ID, P.PRODUCT_NAME,
       (P.PRICE * SUM(O.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT P
         JOIN FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;

---

SELECT A.PRODUCT_ID, B.PRODUCT_NAME,
       (SUM(A.AMOUNT) * B.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER A
         JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
