-- Table
-- ANIMAL_INS ( ANIMAL_ID, DATETIME, NAME )
-- ANIMAL_OUTS ( ANIMAL_ID, DATETIME, NAME )

-- 조건 : 보호 시작일 보다 입양일이 더 빠른 동물
-- 정렬 : 보호 시작일이 빠른 순

SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_OUTS O
        JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE O.DATETIME < I.ANIMAL_ID
ORDER BY I.DATETIME ASC;