-- 없어진 기록 찾기

-- Table
-- ANIMAL_INS (ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME(NULLABLE), SEX_UPON_INTAKE)
-- ANIMAL_OUTS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME(NULLABLE), SEX_UPON_OUTCOME)

-- ANIMAL_OUTS 에는 있는데 ANIMAL_INS 에는 없는 ANIMAL_ID, NAME 을 ANIMAL_ID ASC

SELECT OUTS.ANIMAL_ID, OUTS.NAME
    FROM ANIMAL_OUTS AS OUTS
        LEFT JOIN ANIMAL_INS AS INS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE INS.ANIMAL_ID IS NULL;

------

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
)